Update Commbox.json
commbox-io/api pull request #10
Opened 2022-08-08 14:22 UTC by lital-r

2022-08-14 04:42 UTC, YechielHadad requested changes
I couldn't find many error messages in this PR that the GetContentForTemplateMessage/ValidatePhoneNumber/SendWithoutSave methods retrieve.
Talk to me f2f if this is not clear.

2022-08-14 06:49 UTC, lital-r commented
> GetContentForTemplateMessage

they are all under the same status -400 you can add only one example in the swagger..

2022-08-16 05:07 UTC, YechielHadad requested changes

2022-08-16 05:07 UTC, YechielHadad commented on Commbox.json
> +                      "example": "Partial Content"
400 can't be Partial Content.
There are many optional descriptions. Choose one of them from the code.

2022-08-16 11:30 UTC, YechielHadad approved these changes

2022-08-16 11:30 UTC, merged